### ISSUE TITLE
Should this plugin be updated to allow for update within wp-admin plugins

### ISSUE THREAD

**Issue by binarygary** [FixUpFox/Digital-Garden#12]
To avoid having to grab a zip file every time.

I guess that also leads to a conversation about versioning so the update is visible.

Any strong thoughts? Or better to get something in place and then refine as needed?

**Comment by davidwolfpaw** [comment]
I think that would be a good idea. I admit that I've never done this but I imagine that there are some existing libraries created by the community to use.

As far as versioning goes, I have a PHP constant to define the version. All of the assets are loaded using that constant.

**Comment by davidwolfpaw** [comment]
@binarygary I used the following guide, since it was newly published and seemed much smaller than some other tools.
https://jackwhitworth.com/blog/hosting-updateable-wordpress-plugins-on-github/

I also added this tool to create a distribution archive, for this and future plugins
https://www.tannerrecord.com/easily-zip-wordpress-plugins-with-wp-cli-dist-archive/

And this is an example of it in action on another plugin of mine, which I confirmed it working on.
https://github.com/davidwolfpaw/GitHub-Repo-Card-Block

If this looks good to you I can incorporate into this plugin for future updates (after one more manual one to include it)

**Comment by binarygary** [comment]
💯 :shipit: 
I'm excited to see this working!

**Comment by davidwolfpaw** [comment]
@binarygary I've created a new release with props to you, updated `.gitignore` and a new `.distignore` and `readme.md`.

The one issue that I didn't think about until creating the release: this method doesn't work on a private repo 😅

I also moved the repo to my business profile, out of my personal profile.

**Comment by davidwolfpaw** [comment]
@binarygary Ok, for the moment I've set it to update from my personal site just to have a working feature to try 😅
