### ISSUE TITLE
Hashtags in content link to the Note Tag archive rather than a filtered view

### ISSUE THREAD

**Issue by binarygary** [FixUpFox/Digital-Garden#2]
When the content is filtered in `convert_hashtags_to_links` the link goes to the note tag archive page. 
I think it would make more sense to a user to end up back on the Digital Garden page with the tag IDs appended to the URL.

1. Does that behavior make more sense?
2. Given that the Digital Garden block can be on any page, is it enough to link to the most recent published page that has a Digital Garden block? (the initially created page ID exists under option digital_garden_page_id)

**Comment by davidwolfpaw** [comment]
1. This makes sense @binarygary and I've merged it.

2. Since it can be on any page, that's a good question. I did not consider that multiple pages would have the block, but until we can create a custom page template in a plugin easily, that's the method that I was using to add the block.

In the future, I would like to have a page automatically created (such as "Events" with Events Calendar Pro, or "Shop" with WooCommerce), and have that as a template in the Full Site Editor. Then I would use the assumption of that as the canonical page to link to.
